name: Test
on:
  push:
  pull_request:
env:
  FORCE_COLOR: 2
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12,14,16]
    name: Build&Test,Node.js ${{ matrix.node-version }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm i --registry https://registry.npmmirror.com
      - name: Run test & lint
        run: pnpm test && pnpm lint
      - name: Build
        run: pnpm build
